export const STORYBLOK_UPD_CURRENT = 'STORYBLOK_UPD_CURRENT'
export const STORYBLOK_RESET_CURRENT = 'STORYBLOK_RESET_CURRENT'
export const STORYBLOK_UPD_GLOBAL = 'STORYBLOK_UPD_GLOBAL'
export const STORYBLOK_RESET_GLOBAL = 'STORYBLOK_RESET_GLOBAL'
